package com.electronicstore.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.mail.MailSender;
import org.springframework.mail.SimpleMailMessage;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.ModelAndView;

import com.electronicbackend.dao.UserDAO;
import com.electronicbackend.dto.User;

@Controller
public class LoginRegisterController {
	@Autowired
	MailSender mailsender;

	@Autowired
	UserDAO userdao;

	@RequestMapping(value = { "/userregister" })
	public ModelAndView oTP(@RequestParam("username") String username, @RequestParam("firstname") String firstname,
			@RequestParam("lastname") String lastname, @RequestParam("number") String number,
			@RequestParam("email") String email, @RequestParam("password") String password) {
		ModelAndView mv = new ModelAndView("check");
		mv.addObject("title", "checkOTP");
		int otp = (int) (Math.random() * 9000) + 100000;
		mv.addObject("username", username);
		mv.addObject("firstname", firstname);
		mv.addObject("lastname", lastname);
		mv.addObject("number", number);
		mv.addObject("email", email);
		mv.addObject("password", password);
		mv.addObject("otp", otp);
		SimpleMailMessage mail = new SimpleMailMessage();
		mail.setFrom("theelectronicstore29@gmail.com");
		mail.setTo(email);
		mail.setSubject("One Time Password");
		mail.setText("Dear "+firstname+" "+lastname+",\n\nyour one time password(OTP) for your Registration is " + otp+"\nthis message is generated by the system so please don't relpy to this email\n\nThanks & Regards\n The Electronic Store");
		try {
			mailsender.send(mail);
		} catch (Exception e) {
			e.printStackTrace();
			System.out.println("Can't send the message");
		}
		return mv;
	}

	@RequestMapping(value = { "/resend/otp" })
	public ModelAndView reSendOTP(@RequestParam("username") String username,
			@RequestParam("firstname") String firstname, @RequestParam("lastname") String lastname,
			@RequestParam("number") String number, @RequestParam("email") String email,
			@RequestParam("password") String password) {
		ModelAndView mv = new ModelAndView("check");
		mv.addObject("title", "checkOTP");
		int otp = (int) (Math.random() * 9000) + 100000;
		mv.addObject("username", username);
		mv.addObject("firstname", firstname);
		mv.addObject("lastname", lastname);
		mv.addObject("number", number);
		mv.addObject("email", email);
		mv.addObject("password", password);
		mv.addObject("otp", otp);
		SimpleMailMessage mail = new SimpleMailMessage();
		mail.setFrom("theelectronicstore29@gmail.com");
		mail.setTo(email);
		mail.setSubject("One Time Password");
		mail.setText("Dear "+firstname+" "+lastname+",\n\nyour one time password(OTP) for your Registration is " + otp+"\nthis message is generated by the system so please don't relpy to this email\n\nThanks & Regards\n The Electronic Store");
		try {
			mailsender.send(mail);
		} catch (Exception e) {
			e.printStackTrace();
			System.out.println("Can't send the message");
		}
		return mv;
	}

	@RequestMapping(value = { "/adduser" })
	public ModelAndView addUser(@RequestParam("username") String username, @RequestParam("firstname") String firstname,
			@RequestParam("lastname") String lastname, @RequestParam("number") String number,
			@RequestParam("email") String email, @RequestParam("password") String password) {
		ModelAndView mv = new ModelAndView("page");
		mv.addObject("title", "Login");
		mv.addObject("userClickLogin", true);

		User user = new User();
		user.setActive(true);
		user.setEmail(email);
		user.setFirstName(firstname);
		user.setLastName(lastname);
		user.setRole("user");
		user.setUsername(username);
		user.setPassword(password);
		user.setContactNumber(number);
		userdao.insertUser(user);
		return mv;
	}
	
	@RequestMapping(value={"/forgetpassword"})
	public ModelAndView fogetPassword()
	{
		ModelAndView mv=new ModelAndView("forgetPassword");
		mv.addObject("title", "forgetpassword");
		return mv;
	}
	
	@RequestMapping(value = { "/forgetpassword/otp" })
	public ModelAndView forgetPasswordOTP(@RequestParam("username") String username) 
	{
		ModelAndView mv = new ModelAndView("forgetPasswordCheck");
		mv.addObject("title", "OTP");
		mv.addObject("userClickHome", true);
		User user = userdao.getUserByUsername(username);
		String email=user.getEmail();
		String firstname=user.getFirstName();
		String lastname=user.getLastName();
		mv.addObject("email",email);
		mv.addObject("username", username);
		int otp = (int) (Math.random() * 9000) + 100000;
		mv.addObject("otp",otp);
		SimpleMailMessage mail = new SimpleMailMessage();
		mail.setFrom("theelectronicstore29@gmail.com");
		mail.setTo(email);
		mail.setSubject("One Time Password");
		mail.setText("Dear "+firstname+" "+lastname+",\n\nyour one time password(OTP) for Changing your password is " + otp+"\nthis message is generated by the system so please don't relpy to this email\n\nThanks & Regards\n The Electronic Store");
		try {
			mailsender.send(mail);
		} catch (Exception e) {
			e.printStackTrace();
			System.out.println("Can't send the message");
		}

		return mv;
	}
	@RequestMapping(value = { "/forgetpassword/resend/forgetpasswordotp" })
	public ModelAndView forgetPasswordReSendOTP(@RequestParam("username") String username) 
	{
		ModelAndView mv = new ModelAndView("forgetPasswordCheck");
		mv.addObject("title", "OTP");
		mv.addObject("userClickHome", true);
		User user = userdao.getUserByUsername(username);
		String email=user.getEmail();
		String firstname=user.getFirstName();
		String lastname=user.getLastName();
		mv.addObject("email",email);
		mv.addObject("username", username);
		int otp = (int) (Math.random() * 9000) + 100000;
		mv.addObject("otp",otp);
		SimpleMailMessage mail = new SimpleMailMessage();
		mail.setFrom("theelectronicstore29@gmail.com");
		mail.setTo(email);
		mail.setSubject("One Time Password");
		mail.setText("Dear "+firstname+" "+lastname+",\n\nyour one time password(OTP) for Changing your password is " + otp+"\nthis message is generated by the system so please don't relpy to this email\n\nThanks & Regards\n The Electronic Store");
		try {
			mailsender.send(mail);
		} catch (Exception e) {
			e.printStackTrace();
			System.out.println("Can't send the message");
		}

		return mv;
	}
	
	@RequestMapping(value={"/newpassword"})
	public ModelAndView newPassword(@RequestParam("username") String username)
	{
		ModelAndView mv=new ModelAndView("changePassword");
		mv.addObject("title", "new-password");
		mv.addObject("username", username);
		return mv;
	}
	@RequestMapping(value={"/update/password"})
	public ModelAndView updatePassword(@RequestParam("password") String password,@RequestParam("username") String username)
	{
		ModelAndView mv=new ModelAndView("page");
		mv.addObject("title", "new-password");
		User user = userdao.getUserByUsername(username);
		user.setPassword(password);
		userdao.updateUser(user);
		return mv;
	}
	
	
}
